apiVersion: v1
kind: Template
metadata:
  name: systemd-crond
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: null
    name: systemd
- apiVersion: v1
  allowHostDirVolumePlugin: true
  allowHostIPC: false
  allowHostNetwork: false
  allowHostPID: false
  allowHostPorts: false
  allowPrivilegedContainer: false
  allowedCapabilities: null
  defaultAddCapabilities: null
  fsGroup:
    type: MustRunAs
  users:
  - system:serviceaccount:systemd:systemd
  kind: SecurityContextConstraints
  metadata:
    annotations:
      kubernetes.io/description: systemd-restricted denies access to most host features and requires
        pods to be run with a UID, and SELinux context that are allocated to the namespace.
    creationTimestamp: null
    name: systemd-restricted
  priority: null
  readOnlyRootFilesystem: false
  requiredDropCapabilities:
  - KILL
  - MKNOD
  - SYS_CHROOT
  runAsUser:
    type: MustRunAsRange
  seLinuxContext:
    type: MustRunAs
  supplementalGroups:
    type: RunAsAny
  volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - secret
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: systemd-crond
    name: systemd-crond
  spec:
    dockerImageRepository: docker.io/tchughesiv/systemd-crond
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'docker.io/tchughesiv/systemd-crond:latest'
      generation: 2
      importPolicy:
        scheduled: true
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 6
    labels:
      app: systemd-crond
    name: systemd-crond
  spec:
    replicas: 1
    selector:
      app: systemd-crond
      deploymentconfig: systemd-crond
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        creationTimestamp: null
        labels:
          app: systemd-crond
          deploymentconfig: systemd-crond
      spec:
        containers:
        - image: systemd-crond
          imagePullPolicy: Always
          name: systemd-crond
          resources: {}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /sys/fs/cgroup
            name: cgroup
          - mountPath: /run
            name: run
          - mountPath: /tmp
            name: tmp
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        serviceAccount: systemd
        serviceAccountName: systemd
        terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /sys/fs/cgroup
          name: cgroup
        - emptyDir: {}
          name: run
        - emptyDir: {}
          name: tmp
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - systemd-crond
        from:
          kind: ImageStreamTag
          name: systemd-crond:latest
      type: ImageChange