#!/bin/sh
set -x
MASK_JOBS="sys-fs-fuse-connections.mount systemd-initctl.socket getty.target"
systemctl mask ${MASK_JOBS}
for i in ${MASK_JOBS};do find /usr/lib/systemd/ -iname $i | grep ".wants" | xargs rm -f; done
rm -f /etc/fstab
ln -fs /usr/local/bin/systemd_entrypoint /sbin/init