apiVersion: v1
kind: Template
metadata:
  name: systemd-crond
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: null
    name: systemd
- apiVersion: v1
  allowHostDirVolumePlugin: false
  allowHostIPC: false
  allowHostNetwork: false
  allowHostPID: false
  allowHostPorts: false
  allowPrivilegedContainer: false
  allowedCapabilities: null
  defaultAddCapabilities: null
  fsGroup:
    type: MustRunAs
  users:
  - system:serviceaccount:systemd:systemd
  kind: SecurityContextConstraints
  metadata:
    annotations:
      kubernetes.io/description: systemd-restricted denies access to all host features and requires
        pods to be run with a UID, and SELinux context that are allocated to the namespace. This
        is the second most restrictive SCC.
    creationTimestamp: null
    name: systemd-restricted
  priority: null
  readOnlyRootFilesystem: false
  requiredDropCapabilities:
  - KILL
  - MKNOD
  - SYS_CHROOT
  runAsUser:
    type: MustRunAsRange
  seLinuxContext:
    type: MustRunAs
  supplementalGroups:
    type: RunAsAny
  volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - secret
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: systemd-crond
    name: systemd-crond
  spec:
    tags:
    - name: "systemd-crond"
- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    name: "systemd-crond" 
  spec:
    source:
      git:
        uri: https://github.com/tchughesiv/systemd-crond
    strategy: 
      type: "Docker"
    output:
      to:
        kind: "ImageStreamTag"
        name: "systemd-crond:latest"
    triggers:
    - generic:
        secret: b725254e6534fd70
      type: Generic
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 6
    labels:
      app: systemd-crond
    name: systemd-crond
  spec:
    replicas: 1
    selector:
      app: systemd-crond
      deploymentconfig: systemd-crond
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        creationTimestamp: null
        labels:
          app: systemd-crond
          deploymentconfig: systemd-crond
      spec:
        containers:
        - image: systemd-crond
          imagePullPolicy: Always
          name: systemd-crond
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        serviceAccount: systemd
        serviceAccountName: systemd
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - systemd-crond
        from:
          kind: ImageStreamTag
          name: systemd-crond:latest
      type: ImageChange